### ISSUE TITLE
Mismatch between version in the DESCRIPTION and github release

### ISSUE THREAD

**Issue by tomsing1** [rrrlw/helixvis#8]
The DESCRIPTION file currently lists version `1.0.0` but the last github release is `0.9`.

https://github.com/rrrlw/helixvis/blob/33103cd9d6cbff7cc3374fb92f312838f564e747/DESCRIPTION#L4

**Comment by rrrlw** [comment]
Fixed with [this release](https://github.com/rrrlw/helixvis/releases/tag/v1.0.0). Thank you!
